import { useEffect, useState } from 'react';
import AppLayout from '../components/AppLayout';
import { KPIGrid } from '../components/KPICard';
import SalesTrendChart from '../components/charts/SalesTrendChart';
import TopCategoryChart from '../components/charts/TopCategoryChart';
import StateRevenueChart from '../components/charts/StateRevenueChart';
import CategoryRevenueChart from '../components/charts/CategoryRevenueChart';
import { useDashboardData } from '../hooks/useDashboardData';
import { getAdminDashboard } from '../api/dashboard';

export default function AdminDashboard() {
  const { 
    kpi,salesTrend,topCategory,stateRevenue,categoryRevenue,loading,error} = useDashboardData();
  const [welcome, setWelcome] = useState(null);

  useEffect(() => {
    getAdminDashboard().then(setWelcome).catch(() => setWelcome(null));
  }, []);

  return (
    <AppLayout
      eyebrow="Administrator"
      title="System overview"
      subtitle={welcome?.message || 'Full visibility across users, sales, and inventory.'}
    >
      {error && <div className="mm-alert-banner">{error}</div>}
      {loading ? (
        <p className="mm-loading-tag">Loading dashboard…</p>
      ) : (
        <>
          <KPIGrid data={kpi} />

          <div className="mm-panel-grid-2">
            <div className="mm-panel">
              <div className="mm-panel-title">Sales trend</div>
              <div className="mm-panel-sub">Revenue by month</div>
              <SalesTrendChart data={salesTrend} />
            </div>
            <div className="mm-panel">
              <div className="mm-panel-title">
                Top category{topCategory ? `: ${topCategory['Top Selling Category']}` : ''}
              </div>
              <div className="mm-panel-sub">Units sold by category</div>
              <TopCategoryChart data={topCategory?.['Category Wise Sales']} />
            </div>
          </div>

          <div className="mm-panel">
            <div className="mm-panel-title">
              Revenue by state{stateRevenue ? ` — top: ${stateRevenue['Highest Revenue State']}` : ''}
            </div>
            <div className="mm-panel-sub">Where your customers are buying from</div>
            <StateRevenueChart data={stateRevenue?.['State Wise Revenue']} />
          </div>
          <div className="mm-panel">
            <div className="mm-panel-title">
              Revenue by Category
            {categoryRevenue
              ? ` — top: ${categoryRevenue["Highest Revenue Category"]}`
              : ""}
            </div>

            <div className="mm-panel-sub">
               Revenue generated by each product category
            </div>

            <CategoryRevenueChart
               data={categoryRevenue?.["Category Wise Revenue"]}
           />
          </div>
        </>
      )}
    </AppLayout>
  );
}
